apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: docentcafedry/tickets
          env:
            - name: jwtSecret
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: jwtSecret
            - name: mongodb
              value: "mongodb://mongo-tickets-serv:27017/tickets"
            - name: MY_PODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_IP
              value: "ticketing"
            - name: NATS_URL
              value: "http://nats-streaming-serv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-serv
spec:
  selector:
    app: tickets
  ports:
    - port: 4000
      targetPort: 4000
