name: expiration-depl

on:
  push:
    branches:
      - main
    paths:
      - "expiration/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd expiration && docker build -t docentcafedry/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push docentcafedry/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.YOUR_DIGITALOCEAN_ACCESS_TOKEN_VARIABLE_NAME }}
      - run: doctl kubernetes cluster kubeconfig save ticketing-cluster
      - run: kubectl rollout restart deployment expiration-depl
